id: I34DDBA31
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T15:16:36+00:00'
last_modified: '2022-06-08T06:40:56.905145+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS19691
  title: བསོད་ནམས་མཐའ་ཡས་ཀྱི་རྣམ་ཐར་འདྲ་འབག་ཐར་ལམ་དགྱེས་པའི་རྒྱང་གླུ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    9A44:
      image_group_id: I8LS19693
      title: ''
      total_pages: 46
      order: 1
      base_file: 9A44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
